// Package frontend embeds the built SvelteKit admin SPA.
// The build/ directory is generated by running `pnpm build` in this directory.
package frontend

import (
	"embed"
	"io/fs"
	"net/http"
)

//go:embed build
var buildFS embed.FS

// Handler returns an HTTP handler that serves the built admin SPA.
// Paths not matching a real file fall back to 200.html so that
// client-side routing works for all /admin/* subroutes.
func Handler() http.Handler {
	sub, err := fs.Sub(buildFS, "build")
	if err != nil {
		panic("frontend: fs.Sub: " + err.Error())
	}
	return &spaHandler{fs: http.FS(sub)}
}

type spaHandler struct {
	fs http.FileSystem
}

func (h *spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	f, err := h.fs.Open(r.URL.Path)
	if err == nil {
		st, statErr := f.Stat()
		f.Close()
		// Treat directories as not-found so the SPA shell handles the route
		// instead of http.FileServer rendering a directory listing.
		if statErr == nil && st.IsDir() {
			err = fs.ErrNotExist
		}
	}
	if err != nil {
		r2 := *r
		r2.URL.Path = "/200.html"
		http.FileServer(h.fs).ServeHTTP(w, &r2)
		return
	}
	http.FileServer(h.fs).ServeHTTP(w, r)
}
